# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Dropbox\hobby\Modding\Programs\Github\My Repos\Antistasi_PhoneBook_tool\UI\conf_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Gid_Qt_helpers.Gidgets import DragDropLineEdit

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(509, 356)
        Dialog.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(5, 5, 5, 5)
        self.formLayout.setObjectName("formLayout")
        self.inputconf_antistasipath_lineedit = DragDropLineEdit(Dialog)
        self.inputconf_antistasipath_lineedit.setObjectName("inputconf_antistasipath_lineedit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.inputconf_antistasipath_lineedit)
        self.inputconf_functionspath_lineedit = DragDropLineEdit(Dialog)
        self.inputconf_functionspath_lineedit.setObjectName("inputconf_functionspath_lineedit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.inputconf_functionspath_lineedit)
        self.inputconf_antistasipath_filedialog_button = QtWidgets.QToolButton(Dialog)
        self.inputconf_antistasipath_filedialog_button.setObjectName("inputconf_antistasipath_filedialog_button")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.inputconf_antistasipath_filedialog_button)
        self.inputconf_functionspath_filedialog_button = QtWidgets.QToolButton(Dialog)
        self.inputconf_functionspath_filedialog_button.setObjectName("inputconf_functionspath_filedialog_button")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.inputconf_functionspath_filedialog_button)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_6)
        self.verticalLayout.addLayout(self.formLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.conf_buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.conf_buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.conf_buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.conf_buttonBox.setObjectName("conf_buttonBox")
        self.gridLayout.addWidget(self.conf_buttonBox, 0, 1, 2, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setContentsMargins(5, 5, 5, 5)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_3)
        self.outputconf_standardfolder_filedialog_button = QtWidgets.QToolButton(Dialog)
        self.outputconf_standardfolder_filedialog_button.setObjectName("outputconf_standardfolder_filedialog_button")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.outputconf_standardfolder_filedialog_button)
        self.outputconf_standardfolder_lineedit = DragDropLineEdit(Dialog)
        self.outputconf_standardfolder_lineedit.setObjectName("outputconf_standardfolder_lineedit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.outputconf_standardfolder_lineedit)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_4)
        self.outputconf_standardname_lineedit = QtWidgets.QLineEdit(Dialog)
        self.outputconf_standardname_lineedit.setObjectName("outputconf_standardname_lineedit")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.outputconf_standardname_lineedit)
        self.verticalLayout_2.addLayout(self.formLayout_2)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.conf_buttonBox.accepted.connect(Dialog.accept)
        self.conf_buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Input Configuration"))
        self.inputconf_antistasipath_filedialog_button.setText(_translate("Dialog", "..."))
        self.inputconf_functionspath_filedialog_button.setText(_translate("Dialog", "..."))
        self.label_5.setText(_translate("Dialog", "Antistasi Folder:"))
        self.label_6.setText(_translate("Dialog", "Functions Folder"))
        self.label_2.setText(_translate("Dialog", "Output Configuration"))
        self.label_3.setText(_translate("Dialog", "standard Output Folder"))
        self.outputconf_standardfolder_filedialog_button.setText(_translate("Dialog", "..."))
        self.label_4.setText(_translate("Dialog", "standard Output Base Name"))

