# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Dropbox\hobby\Modding\Programs\Github\My Repos\Antistasi_PhoneBook_tool\UI\snippet_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(650, 750)
        Dialog.setMinimumSize(QtCore.QSize(650, 750))
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.snippet_output_buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.snippet_output_buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.snippet_output_buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.snippet_output_buttonBox.setObjectName("snippet_output_buttonBox")
        self.gridLayout.addWidget(self.snippet_output_buttonBox, 0, 1, 2, 1)
        self.snippet_output_clipboard_button = QtWidgets.QPushButton(Dialog)
        self.snippet_output_clipboard_button.setObjectName("snippet_output_clipboard_button")
        self.gridLayout.addWidget(self.snippet_output_clipboard_button, 1, 0, 1, 1)
        self.snippet_output_textedit = QtWidgets.QTextEdit(Dialog)
        self.snippet_output_textedit.setObjectName("snippet_output_textedit")
        self.gridLayout.addWidget(self.snippet_output_textedit, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.snippet_output_buttonBox.accepted.connect(Dialog.accept)
        self.snippet_output_buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.snippet_output_clipboard_button.setText(_translate("Dialog", "copy snippets to Clipboard"))
