# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'python\UI\As_phonebook_pyQT_temp.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(985, 678)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(400, 20, 501, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Input_name = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.Input_name.setObjectName("Input_name")
        self.verticalLayout.addWidget(self.Input_name)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(190, 20, 191, 80))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.fixedtext1 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.fixedtext1.setFrame(False)
        self.fixedtext1.setObjectName("fixedtext1")
        self.verticalLayout_2.addWidget(self.fixedtext1)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 120, 891, 431))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.graphviz_query_result = QtWidgets.QGraphicsView(self.gridLayoutWidget)
        self.graphviz_query_result.setObjectName("graphviz_query_result")
        self.gridLayout.addWidget(self.graphviz_query_result, 3, 0, 1, 1)
        self.query_result = QtWidgets.QTextBrowser(self.gridLayoutWidget)
        self.query_result.setObjectName("query_result")
        self.gridLayout.addWidget(self.query_result, 3, 1, 1, 1)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(29, 20, 141, 80))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.radio_sqf = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.radio_sqf.setObjectName("radio_sqf")
        self.verticalLayout_3.addWidget(self.radio_sqf)
        self.radio_fnc = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.radio_fnc.setObjectName("radio_fnc")
        self.verticalLayout_3.addWidget(self.radio_fnc)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 985, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSaveAsFile = QtWidgets.QMenu(self.menuFile)
        self.menuSaveAsFile.setObjectName("menuSaveAsFile")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuInitialize = QtWidgets.QMenu(self.menubar)
        self.menuInitialize.setObjectName("menuInitialize")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionInitializeDatabase = QtWidgets.QAction(MainWindow)
        self.actionInitializeDatabase.setObjectName("actionInitializeDatabase")
        self.actionSetPath = QtWidgets.QAction(MainWindow)
        self.actionSetPath.setObjectName("actionSetPath")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionSaveAsHeader = QtWidgets.QAction(MainWindow)
        self.actionSaveAsHeader.setObjectName("actionSaveAsHeader")
        self.actionSaveAsTxtFile = QtWidgets.QAction(MainWindow)
        self.actionSaveAsTxtFile.setObjectName("actionSaveAsTxtFile")
        self.actionSaveTheDiagram = QtWidgets.QAction(MainWindow)
        self.actionSaveTheDiagram.setObjectName("actionSaveTheDiagram")
        self.actionOpenIniFile = QtWidgets.QAction(MainWindow)
        self.actionOpenIniFile.setObjectName("actionOpenIniFile")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.menuSaveAsFile.addAction(self.actionSaveAsTxtFile)
        self.menuSaveAsFile.addAction(self.actionSaveTheDiagram)
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addAction(self.menuSaveAsFile.menuAction())
        self.menuFile.addAction(self.actionSaveAsHeader)
        self.menuSettings.addAction(self.actionSetPath)
        self.menuSettings.addAction(self.actionSettings)
        self.menuInitialize.addAction(self.actionInitializeDatabase)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuInitialize.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.fixedtext1.setText(_translate("MainWindow", "Name of the Sqf file:"))
        self.radio_sqf.setText(_translate("MainWindow", "Sqf file Input"))
        self.radio_fnc.setText(_translate("MainWindow", "Fnc name input"))
        self.menuFile.setTitle(_translate("MainWindow", "file"))
        self.menuSaveAsFile.setTitle(_translate("MainWindow", "save as file"))
        self.menuSettings.setTitle(_translate("MainWindow", "settings"))
        self.menuInitialize.setTitle(_translate("MainWindow", "initialize"))
        self.actionInitializeDatabase.setText(_translate("MainWindow", "initialize Database"))
        self.actionSetPath.setText(_translate("MainWindow", "set path"))
        self.actionClose.setText(_translate("MainWindow", "close"))
        self.actionSaveAsHeader.setText(_translate("MainWindow", "save as header"))
        self.actionSaveAsTxtFile.setText(_translate("MainWindow", "save as txt file"))
        self.actionSaveTheDiagram.setText(_translate("MainWindow", "save the diagram"))
        self.actionOpenIniFile.setText(_translate("MainWindow", "open .ini file"))
        self.actionSettings.setText(_translate("MainWindow", "settings"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
