# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Dropbox\hobby\Modding\Programs\Github\My Repos\Antistasi_PhoneBook_tool\UI\Antistasi_PhoneBook_tool.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 180, 731, 371))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Output_window = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.Output_window.setReadOnly(True)
        self.Output_window.setObjectName("Output_window")
        self.horizontalLayout.addWidget(self.Output_window)
        self.graphicsView = QtWidgets.QGraphicsView(self.horizontalLayoutWidget)
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout.addWidget(self.graphicsView)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 10, 731, 161))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.input_search_term = QtWidgets.QLineEdit(self.tab)
        self.input_search_term.setGeometry(QtCore.QRect(130, 20, 341, 23))
        self.input_search_term.setObjectName("input_search_term")
        self.start_query = QtWidgets.QPushButton(self.tab)
        self.start_query.setGeometry(QtCore.QRect(280, 60, 121, 27))
        self.start_query.setObjectName("start_query")
        self.output_diagram_check = QtWidgets.QCheckBox(self.tab)
        self.output_diagram_check.setGeometry(QtCore.QRect(420, 60, 191, 22))
        self.output_diagram_check.setObjectName("output_diagram_check")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(30, 20, 111, 20))
        self.label.setObjectName("label")
        self.output_full_path_check = QtWidgets.QCheckBox(self.tab)
        self.output_full_path_check.setGeometry(QtCore.QRect(480, 20, 231, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.output_full_path_check.setFont(font)
        self.output_full_path_check.setObjectName("output_full_path_check")
        self.create_header_check = QtWidgets.QCheckBox(self.tab)
        self.create_header_check.setGeometry(QtCore.QRect(420, 90, 231, 22))
        self.create_header_check.setObjectName("create_header_check")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.star_query_all = QtWidgets.QPushButton(self.tab_2)
        self.star_query_all.setGeometry(QtCore.QRect(210, 20, 161, 27))
        self.star_query_all.setObjectName("star_query_all")
        self.create_md_check = QtWidgets.QCheckBox(self.tab_2)
        self.create_md_check.setGeometry(QtCore.QRect(410, 20, 131, 23))
        self.create_md_check.setObjectName("create_md_check")
        self.create_csv_check = QtWidgets.QCheckBox(self.tab_2)
        self.create_csv_check.setGeometry(QtCore.QRect(410, 60, 111, 23))
        self.create_csv_check.setObjectName("create_csv_check")
        self.create_html_check = QtWidgets.QCheckBox(self.tab_2)
        self.create_html_check.setEnabled(False)
        self.create_html_check.setGeometry(QtCore.QRect(410, 100, 121, 23))
        self.create_html_check.setObjectName("create_html_check")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        self.menusettings = QtWidgets.QMenu(self.menubar)
        self.menusettings.setObjectName("menusettings")
        self.menurebuild = QtWidgets.QMenu(self.menubar)
        self.menurebuild.setObjectName("menurebuild")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionopen_user_config = QtWidgets.QAction(MainWindow)
        self.actionopen_user_config.setObjectName("actionopen_user_config")
        self.actionset_paths = QtWidgets.QAction(MainWindow)
        self.actionset_paths.setObjectName("actionset_paths")
        self.actionrebuild_Database = QtWidgets.QAction(MainWindow)
        self.actionrebuild_Database.setObjectName("actionrebuild_Database")
        self.menusettings.addAction(self.actionopen_user_config)
        self.menusettings.addAction(self.actionset_paths)
        self.menurebuild.addAction(self.actionrebuild_Database)
        self.menubar.addAction(self.menusettings.menuAction())
        self.menubar.addAction(self.menurebuild.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.start_query.setText(_translate("MainWindow", "find callers"))
        self.output_diagram_check.setToolTip(_translate("MainWindow", "output file location and name must be specified in the config"))
        self.output_diagram_check.setText(_translate("MainWindow", "create diagram?"))
        self.label.setText(_translate("MainWindow", "Search term:"))
        self.output_full_path_check.setToolTip(_translate("MainWindow", "output file location and name must be specified in the config"))
        self.output_full_path_check.setText(_translate("MainWindow", "Results as full file path?"))
        self.create_header_check.setToolTip(_translate("MainWindow", "output file location and name must be specified in the config"))
        self.create_header_check.setText(_translate("MainWindow", "create header for file?"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.star_query_all.setText(_translate("MainWindow", "show every function"))
        self.create_md_check.setText(_translate("MainWindow", "create .md"))
        self.create_csv_check.setText(_translate("MainWindow", "create .csv"))
        self.create_html_check.setText(_translate("MainWindow", "create .html"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.menusettings.setTitle(_translate("MainWindow", "settings"))
        self.menurebuild.setTitle(_translate("MainWindow", "rebuild"))
        self.actionopen_user_config.setText(_translate("MainWindow", "open user config"))
        self.actionset_paths.setText(_translate("MainWindow", "set paths"))
        self.actionrebuild_Database.setText(_translate("MainWindow", "rebuild Database"))
